version: '2'

volumes:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - ../nextcloud-server:/var/www/html
      - ./:/var/www/html/apps/customproperties
      - /Users/stephankoeninger/.nextcloud:/.nextcloud

