on:
  workflow_dispatch:

jobs:
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: "14.x"
#      - run: npm ci
#      - run: npm run test:js
#
#  build:
#    name: Build
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: "14.x"
#      - run: npm ci
#      - run: npm run build

  sign:
    name: Sign
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends openssl sqlite libpq-dev libmysql++-dev libxml2-utils
      - name: Determine version
        run: |
          echo "VERSION=$(xmllint --xpath 'string(/info/version)' appinfo/info.xml)" >> $GITHUB_ENV
      - name: Create archive
        run: |
          touch customproperties_$VERSION.tar.gz
          tar --exclude=customproperties_$VERSION.tar.gz \
              -zcf  customproperties_$VERSION.tar.gz \
              --exclude='./node_modules/' \
              --exclude='./.git/' \
              --exclude='./.github/' \
              --exclude='./.build/' \
              --exclude='./.cache/' \
              --exclude='./.idea/' \
              --exclude='./.github/' \
              .
      - name: Sign
        run: |
          echo "$PRIVATE_KEY" > privatekey.pem
          openssl dgst -sha512 -sign privatekey.pem customproperties_$VERSION.tar.gz | openssl base64
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
