on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run test:js

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build

  sign:
    name: Sign
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends openssl sqlite libpq-dev libmysql++-dev libxml2-utils
      - name: Determine version
        run: echo "VERSION=$(xmllint --xpath 'string(/info/version)' appinfo/info.xml)" > version.txt >> $GITHUB_ENV
      - name: Create archive
        run: |
          env
          touch customproperties_${{ env.VERSION }}.tar.gz
          tar --exclude=customproperties_${{ env.VERSION }}.tar.gz \
              -zcf  customproperties_${{ env.VERSION }}.tar.gz \
              --exclude='./node_modules/' \
              --exclude='./.git/' \
              --exclude='./.github/' \
              --exclude='./.build/' \
              --exclude='./.cache/' \
              --exclude='./.idea/' \
              --exclude='./.github/' \
              .
      - name: Sign
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > privatekey.pem
          openssl dgst -sha512 -sign privatekey.pem customproperties_${{ env.VERSION }}.tar.gz | openssl base64 > signature.txt
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - uses: actions/upload-artifact@v2
        with:
          name: archive
          path: customproperties_${{ env.VERSION }}.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: signature
          path: signature.txt

  release:
    needs: sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: version
      - uses: actions/download-artifact@v2
        with:
          name: archive
      - uses: actions/download-artifact@v2
        with:
          name: signature
      - name: Determine version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: ${{ env.VERSION }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
